[System] # 系统配置
prefixRouter = "api"         # 路由前缀
port = 12480                    # 路由端口
release = false              # 正式环境

[Mysql] # 数据库配置
path = "49.232.114.127"
port = 3306
property = "charset=utf8mb4&parseTime=True&loc=Local"
db = "vampire"
username = "root"
password = "#12bXbTBBhUkfu#PWI7"

[Jwt] # Token校验
signingKey = "ILoveYou"
expiresTime = 10800 # 3小时

[VerifyCode] # 验证码
key = 4      # 验证码的个数
imgWidth = 240
imgHeight = 80

[Email]
address = "jtyoui@qq.com"
secret = "ebjamxrdrxffdbjg"
ssl = false
